// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkfGqqxD9RNM4_8tXkxlGhSiUUTr9R2Zg',
    appId: '1:89398953927:web:a627ee44285a6d5dfc3be2',
    messagingSenderId: '89398953927',
    projectId: 'empirical-radio-426007-j2',
    authDomain: 'empirical-radio-426007-j2.firebaseapp.com',
    storageBucket: 'empirical-radio-426007-j2.appspot.com',
    measurementId: 'G-XBRD946YGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDys3rPh0kmCvn0QnihjTtgD1GlbeLkLR8',
    appId: '1:89398953927:android:2cbee16af0f5ccdbfc3be2',
    messagingSenderId: '89398953927',
    projectId: 'empirical-radio-426007-j2',
    storageBucket: 'empirical-radio-426007-j2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4X3VRtuLnj1B1veNY6Xg4PcgG45REZR4',
    appId: '1:89398953927:ios:8792f0b84b623afefc3be2',
    messagingSenderId: '89398953927',
    projectId: 'empirical-radio-426007-j2',
    storageBucket: 'empirical-radio-426007-j2.appspot.com',
    iosBundleId: 'com.example.btechApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4X3VRtuLnj1B1veNY6Xg4PcgG45REZR4',
    appId: '1:89398953927:ios:8792f0b84b623afefc3be2',
    messagingSenderId: '89398953927',
    projectId: 'empirical-radio-426007-j2',
    storageBucket: 'empirical-radio-426007-j2.appspot.com',
    iosBundleId: 'com.example.btechApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkfGqqxD9RNM4_8tXkxlGhSiUUTr9R2Zg',
    appId: '1:89398953927:web:15cd37e4ffb25f7dfc3be2',
    messagingSenderId: '89398953927',
    projectId: 'empirical-radio-426007-j2',
    authDomain: 'empirical-radio-426007-j2.firebaseapp.com',
    storageBucket: 'empirical-radio-426007-j2.appspot.com',
    measurementId: 'G-K0PRJ9XZ8X',
  );
}
